# Generated by Django 4.1.5 on 2023-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewgivenid', models.IntegerField(max_length=20)),
                ('reviewreceiveid', models.IntegerField(max_length=20)),
                ('comment', models.TextField(max_length=300)),
                ('rating', models.IntegerField(max_length=20)),
                ('bol', models.BooleanField(default=0)),
            ],
        ),
    ]
