# Generated by Django 4.1.5 on 2023-02-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartanother', '0004_ordernew_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='order_complete',
            field=models.BooleanField(default=False),
        ),
    ]
