# Generated by Django 4.1.5 on 2023-02-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartanother', '0006_ordernew_order_final_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernew',
            name='buyer_review_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordernew',
            name='seller_review_complete',
            field=models.BooleanField(default=False),
        ),
    ]
